# Enter your mnemonic here
MNEMONIC = "<YOUR MNEMONIC HERE>"

# Commit Hash of the commit used to build the contracts
COMMIT_HASH = "<COMMIT HASH HERE>"

# Admin address to execute migrations from
ADMIN_ADDRESS = "<ADMIN ADDRESS HERE>"

MAINNET_REST_URL = "https://archway-api.polkachu.com" 
MAINNET_RPC_URL = "https://archway-rpc.polkachu.com"
MAINNET_CHAIN_ID = "archway-1"

# Currently No Testnet Support For This Swap Chain
# TESTNET_REST_URL = "https://api.constantine.archway.io"
# TESTNET_RPC_URL = "https://rpc.constantine.archway.io"
# TESTNET_CHAIN_ID = "constantine-3"

ADDRESS_PREFIX = "archway"
DENOM = "aarch"
GAS_PRICE = 196000000000

# Contract Paths
ENTRY_POINT_CONTRACT_PATH = "../artifacts/skip_api_entry_point-aarch64.wasm"
IBC_TRANSFER_ADAPTER_PATH = "../artifacts/skip_api_ibc_adapter_ibc_hooks-aarch64.wasm"

# SALT USED TO GENERATE A DETERMINSTIC ADDRESS
SALT = "1"

# @DEV MUST CHANGE SALT ACCORDINGLY TO OBTAIN THIS PRE GENERATED ADDRESS
ENTRY_POINT_PRE_GENERATED_ADDRESS = "<PRE GENERATED ADDRESS HERE>"

[[swap_venues]]
name = "archway-hallswap"
hallswap_contract_address = "archway1tjg47350zpgskprjmcm6chuytnx3q893mru8fqg8jakkw2cjwt5s2unkar"
swap_adapter_path = "../artifacts/skip_api_swap_adapter_hallswap-aarch64.wasm"