# Enter your mnemonic here
MNEMONIC = "<YOUR MNEMONIC HERE>"

# Commut Hash
COMMIT_HASH = "4c6211e7b70eee07f17bd1c8f3a000c5b0731b53"

MAINNET_REST_URL = "rest+https://neutron-api.lavenderfive.com" 
MAINNET_CHAIN_ID = "neutron-1"

TESTNET_REST_URL = "rest+https://rest-palvus.pion-1.ntrn.tech"
TESTNET_CHAIN_ID = "pion-1"

ADDRESS_PREFIX = "neutron"
DENOM = "untrn"
GAS_PRICE = 0.01

# Contract Paths
ENTRY_POINT_CONTRACT_PATH = "../artifacts/skip_swap_entry_point-aarch64.wasm"
SWAP_ADAPTER_PATH = "../artifacts/skip_swap_neutron_astroport_swap-aarch64.wasm"
IBC_TRANSFER_ADAPTER_PATH = "../artifacts/skip_swap_neutron_ibc_transfer-aarch64.wasm"

# @DEV MUST CHANGE SALT IN FILE ACCORDINGLY TO OBTAIN THIS PRE GENERATED ADDRESS
ENTRY_POINT_PRE_GENERATED_ADDRESS = "<PRE GENERATED ADDRESS HERE>"

[[swap_venues]]
name = "neutron-astroport"
router_contract_address = "neutron1eeyntmsq448c68ez06jsy6h2mtjke5tpuplnwtjfwcdznqmw72kswnlmm0"