# Enter your mnemonic here
MNEMONIC = "<YOUR MNEMONIC HERE>"

# Commut Hash
COMMIT_HASH = "<COMMIT HASH HERE>"

MAINNET_REST_URL = "https://lcd.osmosis.zone/"
MAINNET_RPC_URL = "https://osmosis-rpc.polkachu.com/"
MAINNET_CHAIN_ID = "osmosis-1"

TESTNET_REST_URL = "https://lcd.osmotest5.osmosis.zone/"
TESTNET_RPC_URL = "https://rpc.testnet.osmosis.zone/"
TESTNET_CHAIN_ID = "osmo-test-5" 

ADDRESS_PREFIX = "osmo"
DENOM = "uosmo"
GAS_PRICE = 0.01

# Contract Paths
ENTRY_POINT_CONTRACT_PATH = "../artifacts/skip_api_entry_point-aarch64.wasm"
SWAP_ADAPTER_PATH = "../artifacts/skip_api_swap_adapter_osmosis_poolmanager-aarch64.wasm"
IBC_TRANSFER_ADAPTER_PATH = "../artifacts/skip_api_ibc_adapter_ibc_hooks-aarch64.wasm"

# SALT USED TO GENERATE A DETERMINSTIC ADDRESS
SALT = "1"

# @DEV MUST CHANGE SALT ACCORDINGLY TO OBTAIN THIS PRE GENERATED ADDRESS
ENTRY_POINT_PRE_GENERATED_ADDRESS = "<PRE GENERATED ADDRESS HERE>"

# ADDRESS GRANTED PERMISSION BY GOVERNANCE TO UPLOAD CONTRACATS
PERMISSIONED_UPLOADER_ADDRESS = "osmo1raa4kyx5ypz75qqk3566c6slx2mw3qzsu6rymw"

[[swap_venues]]
name = "osmosis-poolmanager"
# Testnet name
#name = "testnet-osmosis-poolmanager"