# Enter your mnemonic here
MNEMONIC = "<YOUR MNEMONIC HERE>"

# Commit Hash of the commit used to build the contracts
COMMIT_HASH = "<COMMIT HASH HERE>"

# Admin address to execute migrations from
ADMIN_ADDRESS = "<ADMIN ADDRESS HERE>"

MAINNET_REST_URL = "https://lcd-terra.tfl.foundation"
MAINNET_RPC_URL = "https://terra-rpc.polkachu.com/"
MAINNET_CHAIN_ID = "phoenix-1"

# Currently No Testnet Support For This Swap Chain
# TESTNET_REST_URL = "https://pisco-lcd.terra.dev"
# TESTNET_RPC_URL = "https://terra-testnet-rpc.polkachu.com/"
# TESTNET_CHAIN_ID = "pisco-1"

ADDRESS_PREFIX = "terra"
DENOM = "uluna"
GAS_PRICE = 0.015

# Contract Paths
ENTRY_POINT_CONTRACT_PATH = "../artifacts/skip_api_entry_point-aarch64.wasm"
IBC_TRANSFER_ADAPTER_PATH = "../artifacts/skip_api_ibc_adapter_ibc_hooks-aarch64.wasm"

# SALT USED TO GENERATE A DETERMINSTIC ADDRESS
SALT = "1"

# @DEV MUST CHANGE SALT ACCORDINGLY TO OBTAIN THIS PRE GENERATED ADDRESS
ENTRY_POINT_PRE_GENERATED_ADDRESS = "<PRE GENERATED ADDRESS HERE>"

[[swap_venues]]
name = "terra-astroport"
swap_adapter_path = "../artifacts/skip_api_swap_adapter_astroport-aarch64.wasm"

[[swap_venues]]
name = "terra-white-whale"
swap_adapter_path = "../artifacts/skip_api_swap_adapter_white_whale-aarch64.wasm"

[[swap_venues]]
name = "terra-hallswap"
hallswap_contract_address = "terra1e3nqr8vwu32pzgasraud9avpwdd8phmqgre5kpwlytgedj2emkkq3l67hy"
swap_adapter_path = "../artifacts/skip_api_swap_adapter_hallswap-aarch64.wasm"

# [[testnet_swap_venues]]
# name = "testnet-terra-astroport"
# swap_adapter_path = "../artifacts/skip_api_swap_adapter_astroport-aarch64.wasm"

# [[testnet_swap_venues]]
# name = "testnet-terra-white-whale"
# swap_adapter_path = "../artifacts/skip_api_swap_adapter_white_whale-aarch64.wasm"