[info]
chain_id = "neutron-1"
network = "mainnet"
deploy_date = "18/07/2023 15:34:18"
commit_hash = "4c6211e7b70eee07f17bd1c8f3a000c5b0731b53"

[checksums]
"skip_swap_entry_point-aarch64.wasm" = "57169cdff38440deb5bfa4f6c3f564d3dec3ae06e69e3dc46cc41c3c6d9dad92"
"skip_swap_neutron_astroport_swap-aarch64.wasm" = "e259ceae0b68d957717e19fb49cbc0aee5142e64728ff3d9175c8fc1ff68ed21"
"skip_swap_neutron_ibc_transfer-aarch64.wasm" = "8a8ed75e29e668beb0cb1b4c82935d67143c20234fd562ff9eecef86a6427aac"
"skip_swap_osmosis_ibc_transfer-aarch64.wasm" = "fd5ff827d82f7ad80c5ed61b7a8449a2ced99c6f0e813358b9867e443ebd82a3"
"skip_swap_osmosis_poolmanager_swap-aarch64.wasm" = "0e241fc025a63a88953b677ae6d9ea320c87a48890368bb2d91ee09e074b609b"

[code-ids]
swap_adapter_contract_code_id = 111
ibc_transfer_adapter_contract_code_id = 112
entry_point_contract_code_id = 113

[contract-addresses]
swap_adapter_contract_address = "neutron1c7w7ezltfjyhvkrtdraee09pmtlpwnffnj7zrpg9yh77z0v5dmzq7dg6pt"
ibc_transfer_adapter_contract_address = "neutron1exel4g6q4y0agdj92ksujlphwentk6lmkw38yc06dq3mxmwet77sttl3j3"
entry_point_contract_address = "neutron1mrm80xxdv8yhrt6gqvx2n638vjh23j023xj5yufha9y02gvskmaq6prr8z"

[tx-hashes]
store_swap_adapter_tx_hash = "B43FFF7AEF57B97971A7C42786EAC32A2A75253A189CFEE78501B1E85E9E0327"
store_ibc_transfer_adapter_tx_hash = "30073E133F79968D770FE93276F2D7BAA1717D86816B98F38B4B39385798F5BC"
store_entry_point_tx_hash = "D93CF9CC1AFA6009162893A014D7B6D9364C9DE5267477D265CF9EFB7FAAE0D6"
instantiate_swap_adapter_tx_hash = "C8CDAB38F789C6FBF7A2CE55D8E327D8FCB0CAD683CC8876CC1F899FB98B444A"
instantiate_ibc_transfer_adapter_tx_hash = "6AF3777A460045BDC81C5F6B3E54D87D4842CF9E314374371AC2F127077B9EB2"
instantiate_entry_point_tx_hash = "4D58BAEAFD7770F6DCD1E1EB6A84DE7E352F50E56594E6AED72EF5C18B093A89"
