[info]
chain_id = "neutron-1"
network = "mainnet"
deploy_date = "14/02/2024 23:19:12"
commit_hash = "d4209d40b8facecc98d3c278d98c2efcb0950815"
salt = "1"

[checksums]
"skip_api_entry_point-aarch64.wasm" = "d18102654c30479b008162010a50a1706f78c1d90914262f135d2507763e5121"
"skip_api_ibc_adapter_ibc_hooks-aarch64.wasm" = "18f6840c4a121babb2080e2db40d001e0578657d4a3bd55a9db88aaac26f79d9"
"skip_api_ibc_adapter_neutron_transfer-aarch64.wasm" = "e46f2dc24a2b48ac0dfa9780e131a507ca6dc1230cfc9bba613a76fcb07c1ce2"
"skip_api_placeholder-aarch64.wasm" = "b8a6cca4e12d1d854ac000082b8d3e6494b6b33e4484bdeeef2ee288adfe71c5"
"skip_api_swap_adapter_astroport-aarch64.wasm" = "ce9039ec7792d71fb9a72ff7c21bbdd7807f5ca2501e9baf3b0954333288bee3"
"skip_api_swap_adapter_lido_satellite-aarch64.wasm" = "b533260f328631fb73754efb5f7a5469b3f1a462c04fb06f610d7768f1f15820"
"skip_api_swap_adapter_osmosis_poolmanager-aarch64.wasm" = "677671365aeda46aca42d137b68a850752c5730c81bcea4ca18045e24f591276"
"skip_api_swap_adapter_white_whale-aarch64.wasm" = "5a88094929f1027fa5287cdbb467040804f02a71773ea12d7f6c8c2f6284b565"

[code-ids]
ibc_transfer_adapter_contract_code_id = "710"
swap_adapter_neutron-astroport_contract_code_id = "711"
swap_adapter_neutron-lido-satellite_contract_code_id = "712"
entry_point_contract_code_id = "713"

[contract-addresses]
ibc_transfer_adapter_contract_address = "neutron15m02lgpakv9paewse3x7cdv5qxhsvsfjsw8j09d7leyx3t65m3ssyrlyr5"
swap_adapter_neutron-astroport_contract_address = "neutron12sga4v7vu79wzpxwt2fccuu7tf6dlz3y2s87g0h7t8a5ln68997q6sgh0x"
swap_adapter_neutron-lido-satellite_contract_address = "neutron1fm3mf8c4xcmtuvphv2le7mld4tdv25dn85e7ms8rq5u9wumrskxsrkazxt"
entry_point_contract_address = "neutron18jgzyha8r25ltxn6u5ng9zajwflhnwzzunlnfunyktjfpextuqfqyjre7j"

[tx-hashes]
store_ibc_transfer_adapter_tx_hash = "f89ad8a510e53dd407279b4176968442e1bbdd8e04747a48286ee29c25ca7c6d"
instantiate_ibc_transfer_adapter_tx_hash = "ac5580d79f765a6630f720e54383e54ac087d5f0e13de8fa7a030902b70460df"
store_swap_adapter_neutron-astroport_tx_hash = "d2fefc3aba587693f4695e1927aaf42aef289679ea4e542046d97dbdb1b9e7fa"
instantiate_swap_adapter_neutron-astroport_tx_hash = "4218b40c9dc5e56ff5fed58b98e822bbbad163525c11b4277b1b0f42ff5ce817"
store_swap_adapter_neutron-lido-satellite_tx_hash = "b4d9026aaf0f26819b655fdb082b240dd6ebc718876f8660e8106f8a6c287fec"
instantiate_swap_adapter_neutron-lido-satellite_tx_hash = "924b6bf3d2b5a9cb5f51c9fd76ec451d6fa80bce8ec98a54c3877fd295956e1b"
store_entry_point_tx_hash = "21c11f1ef756181f653b270f8a7c65875ef1cf9eb7198b3b2716365d710135d9"
instantiate_entry_point_tx_hash = "9c75e20c73072982b1770b9b1f36c39d154766a38bbd330baa9f7859a5914fff"