[info]
chain_id = "pion-1"
network = "testnet"
deploy_date = "18/07/2023 15:11:44"
commit_hash = "4c6211e7b70eee07f17bd1c8f3a000c5b0731b53"

[checksums]
"skip_swap_entry_point-aarch64.wasm" = "57169cdff38440deb5bfa4f6c3f564d3dec3ae06e69e3dc46cc41c3c6d9dad92"
"skip_swap_neutron_astroport_swap-aarch64.wasm" = "e259ceae0b68d957717e19fb49cbc0aee5142e64728ff3d9175c8fc1ff68ed21"
"skip_swap_neutron_ibc_transfer-aarch64.wasm" = "8a8ed75e29e668beb0cb1b4c82935d67143c20234fd562ff9eecef86a6427aac"
"skip_swap_osmosis_ibc_transfer-aarch64.wasm" = "fd5ff827d82f7ad80c5ed61b7a8449a2ced99c6f0e813358b9867e443ebd82a3"
"skip_swap_osmosis_poolmanager_swap-aarch64.wasm" = "0e241fc025a63a88953b677ae6d9ea320c87a48890368bb2d91ee09e074b609b"

[code-ids]
swap_adapter_contract_code_id = 1200
ibc_transfer_adapter_contract_code_id = 1201
entry_point_contract_code_id = 1202

[contract-addresses]
swap_adapter_contract_address = "neutron1hurlj68ult8cq68j7cayg7hpy02wt4rty48x88z0lhw48s4qfqqql4x34n"
ibc_transfer_adapter_contract_address = "neutron10ww4dqrr6hm0fll84jjlz88gnp63c5dwq98dxeq7vujhlhvudmfqen6frv"
entry_point_contract_address = "neutron1mrm80xxdv8yhrt6gqvx2n638vjh23j023xj5yufha9y02gvskmaq6prr8z"

[tx-hashes]
store_swap_adapter_tx_hash = "5035D0790D8B33A55845849A6E219E26C9226F94B84F71D594EA789C7A2E9084"
store_ibc_transfer_adapter_tx_hash = "3592C57B8863EFE546A3E7261D017A83AEC75F323F7EB236B6399FFA2B3C50CD"
store_entry_point_tx_hash = "3D4B490DBD30090F8DE2A4056404AFDE6B0D5C37B35CE3D926EE6E2A7C39CB88"
instantiate_swap_adapter_tx_hash = "AA78F95DD3F4FF50BCED921526E97BBAAFAAC37AEB5203852B08AAA0C9444F0F"
instantiate_ibc_transfer_adapter_tx_hash = "56DFD51153D2ADDDFBD6F1F333A67798BA1C59B97205159A236742CB133B564F"
instantiate_entry_point_tx_hash = "9A63558CFDBDAA7125387FFD9F982EB82D7596BF01CC72643C2724F85D012D70"
